[package]
name = "gitlab-ci-ls"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/alesbrelih/gitlab-ci-ls"
description = "Language server for Gitlab CI"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
lsp-server = "0.7.6"
lsp-types = "0.95.1"
serde_json = "1.0.116"
simple-logging = "2.0.2"
simple_logger = "4.3.3"
tokio = "1.36.0"
anyhow = "1.0.82"
serde = "1.0.199"
git2 = "0.18.3"
tree-sitter = "0.20.10"
tree-sitter-yaml = "0.0.1"
reqwest = { version = "0.12.4", features = ["blocking"] }
regex = "1.10.4"
serde_yaml = "0.9.34"
crc64 = "2.0.0"
clap = { version = "4.5.4", features = ["derive"] }

[lints.clippy]
all = "deny"
pedantic = "deny"
