[package]
name = "gitlab-ci-ls"
version = "0.22.0"
edition = "2021"
repository = "https://github.com/alesbrelih/gitlab-ci-ls"
description = "Language server for Gitlab CI"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
streaming-iterator = "0.1.9"
lsp-server = "0.7.7"
lsp-types = "0.95.1"
serde_json = "1.0.132"
simple-logging = "2.0.2"
simple_logger = "5.0.0"
tokio = "1.40.0"
anyhow = "1.0.90"
serde = "1.0.210"
tree-sitter = "0.24.3"
tree-sitter-yaml = "0.6.1"
reqwest = { version = "0.12.8", features = ["blocking"] }
regex = "1.11.0"
serde_yaml = "0.9.34"
crc64 = "2.0.0"
clap = { version = "4.5.20", features = ["derive"] }

[lints.clippy]
all = "deny"
pedantic = "deny"
